langauge: cpp

before_install:
    - sudo apt-get install libgtest-dev

script:
    - mkdir build && (cd build && cmake ../CMake && make) && mkdir tests/build && mkdir build_gtest && (cd build_gtest && cmake /usr/src/gtest && make) && (cd tests/build && cp ../../build_gtest/libgtest.a . && cmake ../CMake -DLIBRARY_LOCATION=../../build && make && ./nds3tests)
