language: cpp
dist: trusty

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

env:
    - DOXYFILE=doc/api/DoxyfileHTML PATH=$HOME/.local/usr/bin:$PATH

install:
    - ./scripts/travis-install.sh

script:
    - ./scripts/travis-script.sh

after_success:
    - scripts/deploy_doxygen
